<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubyektShakliSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data =  [
            [
                'code' => 'қ0004',
                'name' => 'Ташқи ишлар вазирлиги',
                'description' => '',
                'name_ru' => 'Ташқи ишлар вазирлиги',
                'description_ru' => '',
            ],
            [
                'code' => 'қ0006',
                'name' => 'Таълим вазирлиги',
                'description' => '',
                'name_ru' => 'Таълим вазирлиги',
                'description_ru' => '',
            ],
            [
                'code' => 'қ0009',
                'name' => 'Хусусий ташкилотлар',
                'description' => '',
                'name_ru' => 'Хусусий ташкилотлар',
                'description_ru' => '',
            ],
            [
                'code' => '1010',
                'name' => 'TOSHKENT INVESTITSIYA MAJMUI',
                'description' => '',
                'name_ru' => 'TOSHKENT INVESTITSIYA MAJMUI',
                'description_ru' => '',
            ],
            [
                'code' => '1152',
                'name' => 'VODLON INTERNATIONAL SERVICH',
                'description' => '',
                'name_ru' => 'VODLON INTERNATIONAL SERVICH',
                'description_ru' => '',
            ],
            [
                'code' => '1153',
                'name' => 'OOO"FARTUNA MEBEL SANOAT"',
                'description' => 'OOO"FARTUNA MEBEL SANOAT"',
                'name_ru' => 'OOO"FARTUNA MEBEL SANOAT"',
                'description_ru' => 'OOO"FARTUNA MEBEL SANOAT"',
            ],
            [
                'code' => '91',
                'name' => 'АдБ',
                'description' => 'Адвокатлик бюроси',
                'name_ru' => 'АдБ',
                'description_ru' => 'Адвокатское бюро',
            ],
            [
                'code' => '834',
                'name' => 'АдФ',
                'description' => 'Адвокатлик фирмаси',
                'name_ru' => 'АдФ',
                'description_ru' => 'Адвокатская фирма',
            ],
            [
                'code' => '817',
                'name' => 'АК',
                'description' => 'Акционелик компанияси',
                'name_ru' => 'АК',
                'description_ru' => 'Акционерное Компания',
            ],
            [
                'code' => '5',
                'name' => 'АКБ',
                'description' => 'Акциядорлик тижорат банки',
                'name_ru' => 'АТБ',
                'description_ru' => 'Акционерно-коммерческий банк',
            ],
            [
                'code' => '823',
                'name' => 'АО',
                'description' => 'Акционерлик жамияти',
                'name_ru' => 'АЖ',
                'description_ru' => 'Акционерное общество',
            ],
            [
                'code' => '836',
                'name' => 'АООТ',
                'description' => 'Очиқ турдаги акционерлик жамияти',
                'name_ru' => 'ОТАЖ',
                'description_ru' => 'Акционерное общество открытого типа',
            ],
            [
                'code' => '832',
                'name' => 'АуК',
                'description' => 'Аудиторлик компанияси',
                'name_ru' => 'АуК',
                'description_ru' => 'Аудиторская компания',
            ],
            [
                'code' => '50',
                'name' => 'Банк',
                'description' => 'Банк',
                'name_ru' => 'Банк',
                'description_ru' => 'Банк',
            ],
            [
                'code' => '95',
                'name' => 'Бюдж.',
                'description' => 'Бюджет',
                'name_ru' => 'Бюдж.',
                'description_ru' => 'Бюджет',
            ],
            [
                'code' => '96',
                'name' => 'Бюдж.',
                'description' => '',
                'name_ru' => 'Бюдж.',
                'description_ru' => '',
            ],
            [
                'code' => '851',
                'name' => 'ГНК',
                'description' => 'Давлат нотариал идораси',
                'name_ru' => 'ДНИ',
                'description_ru' => 'Государственная нотариальная контора',
            ],
            [
                'code' => '13',
                'name' => 'Гр.Суд',
                'description' => 'Фуқаролик ишлари бўйича суд',
                'name_ru' => 'Фқ.Суд',
                'description_ru' => 'Суд по гражданским делам',
            ],
            [
                'code' => '11',
                'name' => 'ГУВД',
                'description' => 'Шаҳар ички ишлар бошқармаси',
                'name_ru' => 'ШИИБ',
                'description_ru' => 'Городское Управление Внутренних Дел',
            ],
            [
                'code' => '821',
                'name' => 'ГУП',
                'description' => 'Давлат унитар корхонаси',
                'name_ru' => 'ДУК',
                'description_ru' => 'Государственное унитарное предприятие',
            ],
            [
                'code' => '810',
                'name' => 'ДП',
                'description' => 'Шўъба корхонаси',
                'name_ru' => 'ШК',
                'description_ru' => 'Дочернее предприятие',
            ],
            [
                'code' => '806',
                'name' => 'Дубл ишлатилмасин ГНК',
                'description' => 'Давлат нотариал идораси',
                'name_ru' => 'ДНИ',
                'description_ru' => 'Государственная нотариальная контора',
            ],
            [
                'code' => '1100',
                'name' => 'дубл ишлатилмасин ДП',
                'description' => 'Шўъба корхонаси',
                'name_ru' => 'ШК',
                'description_ru' => 'Дочерное предприятие',
            ],
            [
                'code' => '825',
                'name' => 'ДХО',
                'description' => 'Шўъба хўжалик жамияти',
                'name_ru' => 'ШХЖ',
                'description_ru' => 'Дочернее хозяйственное общество',
            ],
            [
                'code' => '93',
                'name' => 'ЖСК',
                'description' => 'Уй-жой қурилиш кооперативи',
                'name_ru' => 'УЖҚК',
                'description_ru' => 'Жилищно-строительный кооператив',
            ],
            [
                'code' => '819',
                'name' => 'ЖЭК',
                'description' => 'ЖЭК',
                'name_ru' => 'ЖЭК',
                'description_ru' => 'ЖЭК',
            ],
            [
                'code' => '406',
                'name' => 'ЗАО',
                'description' => 'Ёпиқ акциядорлик жамияти',
                'name_ru' => 'ЁАЖ',
                'description_ru' => 'Закрытое акционерное общество',
            ],
            [
                'code' => '60',
                'name' => 'ИП',
                'description' => 'Чет эл корхонаси',
                'name_ru' => 'ЧК',
                'description_ru' => 'Иностранное предприятие',
            ],
            [
                'code' => '6',
                'name' => 'ИП ООО',
                'description' => 'Маъсулияти чекланган жамияти шаклидаги чет эл корхонаси',
                'name_ru' => 'МЧЖ ЧК',
                'description_ru' => 'Иностранное предприятие в форме общества с ограниченной ответственностью',
            ],
            [
                'code' => '97',
                'name' => 'казначейство',
                'description' => '',
                'name_ru' => 'казначейство',
                'description_ru' => '',
            ],
            [
                'code' => '807',
                'name' => 'КБ',
                'description' => 'Тижорат банки',
                'name_ru' => 'ТБ',
                'description_ru' => 'Коммерческий банк',
            ],
            [
                'code' => '816',
                'name' => 'Кл.',
                'description' => 'Клиника',
                'name_ru' => 'Кл.',
                'description_ru' => 'Клиника',
            ],
            [
                'code' => '855',
                'name' => 'КОГГ СНБ',
                'description' => 'КОГГ СНБ',
                'name_ru' => 'КОГГ СНБ',
                'description_ru' => 'КОГГ СНБ',
            ],
            [
                'code' => '80',
                'name' => 'Комп.',
                'description' => 'Компания',
                'name_ru' => 'Комп.',
                'description_ru' => 'Компания',
            ],
            [
                'code' => '844',
                'name' => 'КП',
                'description' => 'Жамоа корхонаси',
                'name_ru' => 'ЖК',
                'description_ru' => 'Коллективное предприятие',
            ],
            [
                'code' => '94',
                'name' => 'КС',
                'description' => 'Кредит уюшмаси',
                'name_ru' => 'КУ',
                'description_ru' => 'Кредитнқй союз',
            ],
            [
                'code' => '90',
                'name' => 'КЭЧ',
                'description' => 'Коммунал фойдаланиш қисми',
                'name_ru' => 'КФҚ',
                'description_ru' => 'Комунально-Эксплуатационная Часть',
            ],
            [
                'code' => '809',
                'name' => 'КЭЧ МОРУз',
                'description' => 'Ўзбекистон Республикаси Мудофаа Вазирлигининг квартирадан фойдаланиш қисми',
                'name_ru' => 'ЎзРес МВ КФҚ',
                'description_ru' => 'Квартирно-эксплуатационная часть Министерство Обороны Республики Узбекистан',
            ],
            [
                'code' => 'қ',
                'name' => 'Министерство',
                'description' => 'Вазирлик',
                'name_ru' => 'Министерство',
                'description_ru' => 'Вазирлик',
            ],
            [
                'code' => '852',
                'name' => 'МОРУз',
                'description' => 'Министерство Обороны',
                'name_ru' => 'МОРУз',
                'description_ru' => 'Министерство Обороны',
            ],
            [
                'code' => '829',
                'name' => 'МСГ',
                'description' => 'Махалла фуқаролар йиғини',
                'name_ru' => 'МФЙ',
                'description_ru' => 'Махаллинский сход граждан',
            ],
            [
                'code' => 'қ0001',
                'name' => 'НОУ',
                'description' => 'NODAVLAT TA\'LIM MUASSASASI',
                'name_ru' => 'NTM',
                'description_ru' => 'Негосударственное образовательное учреждение',
            ],
            [
                'code' => '854',
                'name' => 'ОАКБ',
                'description' => 'Очиқ акциядорлик тижорат банки',
                'name_ru' => 'ОАТБ',
                'description_ru' => 'Открытый акционерно-коммерческий банк',
            ],
            [
                'code' => '811',
                'name' => 'ОАО',
                'description' => 'Очиқ акциядорлик жамияти',
                'name_ru' => 'ОАЖ',
                'description_ru' => 'Открытое акционерное общество',
            ],
            [
                'code' => '845',
                'name' => 'Общество',
                'description' => 'Жамият',
                'name_ru' => 'Жамият',
                'description_ru' => 'Общество',
            ],
            [
                'code' => '841',
                'name' => 'Объединение',
                'description' => 'Бирлашма',
                'name_ru' => 'Бирлашма',
                'description_ru' => 'Объединение',
            ],
            [
                'code' => '99',
                'name' => 'ОПФ',
                'description' => '',
                'name_ru' => 'ОПФ',
                'description_ru' => '',
            ],
            [
                'code' => '305',
                'name' => 'Организация',
                'description' => 'Ташкилот',
                'name_ru' => 'Организация',
                'description_ru' => 'Ташкилот',
            ],
            [
                'code' => '824',
                'name' => 'ПКФ',
                'description' => 'Ишлаб чиқариш тижорат фирмаси',
                'name_ru' => 'ИЧТФ',
                'description_ru' => 'Производственно-коммерческая фирма',
            ],
            [
                'code' => '813',
                'name' => 'Представительство',
                'description' => 'Ваколатхона',
                'name_ru' => 'Представительство',
                'description_ru' => 'Ваколатхона',
            ],
            [
                'code' => '814',
                'name' => 'Районный хакимият',
                'description' => 'Туман хокимлиги',
                'name_ru' => 'Районный хакимият',
                'description_ru' => 'Районный хакимият',
            ],
            [
                'code' => '14',
                'name' => 'РОВД',
                'description' => 'ТИИБ',
                'name_ru' => 'ТИИБ',
                'description_ru' => 'Районный Отдел Внутренних Дел',
            ],
            [
                'code' => 'қ0010',
                'name' => 'Семейное предприятие',
                'description' => 'Оилавий корхонаси',
                'name_ru' => 'Семейное предприятие',
                'description_ru' => 'Оилавий корхонаси',
            ],
            [
                'code' => '808',
                'name' => 'СемП',
                'description' => 'Оилавий корхона',
                'name_ru' => 'ОК',
                'description_ru' => 'Семейная предприятия',
            ],
            [
                'code' => '999',
                'name' => 'СК в форме ООО',
                'description' => 'Масъулияти чеклаган жамияти шаклидаги суғурта копманияси',
                'name_ru' => 'МЧЖ шаклидаги СК',
                'description_ru' => 'Страховая компания в форме общество органиченной ответственности',
            ],
            [
                'code' => '830',
                'name' => 'СНБ',
                'description' => 'Миллий ҳавфсизлик хизмати',
                'name_ru' => 'МХХ',
                'description_ru' => 'Служба национальной безопасности',
            ],
            [
                'code' => '4',
                'name' => 'СП',
                'description' => 'Қўшма корхона',
                'name_ru' => 'ҚК',
                'description_ru' => 'Совместное предприятие',
            ],
            [
                'code' => '840',
                'name' => 'СП ООО',
                'description' => 'ҚК МЧЖ',
                'name_ru' => 'ҚК МЧЖ',
                'description_ru' => 'Совместное предприятие в форме общества с ограниченной ответственностью',
            ],
            [
                'code' => '818',
                'name' => 'Спец-Эксперимент',
                'description' => 'Спец-Эксперимент',
                'name_ru' => 'Спец-Эксперимент',
                'description_ru' => 'Спец-Эксперимент',
            ],
            [
                'code' => '9',
                'name' => 'СПОН',
                'description' => 'Вояга етмаганларга ижтимоий-ҳуқуқий ёрдам кўрсатиш маркази',
                'name_ru' => 'СПОН',
                'description_ru' => 'Центр социально-правовой помощи несовершеннолетним',
            ],
            [
                'code' => '805',
                'name' => 'Суд исполнители',
                'description' => 'Суд ижрочилари',
                'name_ru' => 'Суд исполнители',
                'description_ru' => 'Суд исполнители',
            ],
            [
                'code' => '815',
                'name' => 'Таможня',
                'description' => 'Божхона',
                'name_ru' => 'Таможня',
                'description_ru' => 'Таможня',
            ],
            [
                'code' => '838',
                'name' => 'ТОО',
                'description' => 'Масъулияти чекланган уюшма',
                'name_ru' => 'МЧУ',
                'description_ru' => 'Товарищество ограниченной ответственности',
            ],
            [
                'code' => '405',
                'name' => 'Трест',
                'description' => 'Трест',
                'name_ru' => 'Трест',
                'description_ru' => 'Трест',
            ],
            [
                'code' => '92',
                'name' => 'ТЧСЖ',
                'description' => 'Хусусий уй-жой мулкдорлари ширкати',
                'name_ru' => 'ХУЖМШ',
                'description_ru' => 'Товарищество частных собственников жилья',
            ],
            [
                'code' => '828',
                'name' => 'УП',
                'description' => 'Унитар корхона',
                'name_ru' => 'УК',
                'description_ru' => 'Унитарное предприятие',
            ],
            [
                'code' => '846',
                'name' => 'Управление',
                'description' => 'Бошқарма',
                'name_ru' => 'Управление',
                'description_ru' => 'Управление',
            ],
            [
                'code' => '812',
                'name' => 'Учириб ташлаш керак',
                'description' => 'Учириб ташлаш керак',
                'name_ru' => 'Учириб ташлаш керак',
                'description_ru' => 'Учириб ташлаш керак',
            ],
            [
                'code' => '820',
                'name' => 'Фермерское Хозяйство',
                'description' => 'Фермер хўжалиги',
                'name_ru' => 'Фермерское Хозяйство',
                'description_ru' => 'Фермерское Хозяйство',
            ],
            [
                'code' => '839',
                'name' => 'Фирма',
                'description' => 'Фирма',
                'name_ru' => 'Фирма',
                'description_ru' => 'Фирма',
            ],
            [
                'code' => '98',
                'name' => 'хато киритилган ООО',
                'description' => 'хато киритилган ООО',
                'name_ru' => 'хато киритилган ООО',
                'description_ru' => 'хато киритилган ООО',
            ],
            [
                'code' => 'қ0003',
                'name' => 'Хокимият города Ташкента',
                'description' => 'Тошкент шахар хокимияти',
                'name_ru' => 'Хокимият города Ташкента',
                'description_ru' => 'Хокимият города Ташкента',
            ],
            [
                'code' => '0',
                'name' => 'ЦГУ',
                'description' => 'Давлат хизматлари маркази',
                'name_ru' => 'ДХМ',
                'description_ru' => 'Центр государственных услуг',
            ],
            [
                'code' => '059',
                'name' => 'ЦЕО',
                'description' => 'Ягона дарча маркази',
                'name_ru' => 'ЯДМ',
                'description_ru' => 'Центр единного окна',
            ],
            [
                'code' => '833',
                'name' => 'Частная нотариальная контора',
                'description' => 'Хусусий нотариал идора',
                'name_ru' => 'Хусусий нотариал идора',
                'description_ru' => 'Частная нотариальная контора',
            ],
            [
                'code' => '831',
                'name' => 'Частное предприятие',
                'description' => 'Хусусий корхона',
                'name_ru' => 'ХК',
                'description_ru' => 'Частное предприятие',
            ],
            [
                'code' => '3',
                'name' => 'Частный предприниматель',
                'description' => 'Хусусий тадбиркор',
                'name_ru' => 'ХТ',
                'description_ru' => 'Частный предприниматель',
            ],
            [
                'code' => 'қ0002',
                'name' => 'ЧПП',
                'description' => 'Хусусий ишлаб чикариш корхонаси',
                'name_ru' => 'ХИЧК',
                'description_ru' => 'Частное производственное предприятие',
            ],
            [
                'code' => '2',
                'name' => 'ЧФ',
                'description' => 'Хусусий фирма',
                'name_ru' => 'ХФ',
                'description_ru' => 'Частная фирма',
            ],
            [
                'code' => '12',
                'name' => 'ЮК',
                'description' => 'Юридическая консультация',
                'name_ru' => 'ЮК',
                'description_ru' => 'Юридическая консультация',
            ],
        ];

        DB::table('subyekt_shaklis')->insert($data);
    }
}
